INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (1, 'Toyota Camry', 25000.00, 'Toyota');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (2, 'Honda Accord', 23000.50, 'Honda');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (3, 'Ford Mustang', 35000.75, 'Ford');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (4, 'Chevrolet Silverado', 32000.25, 'Chevrolet');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (5, 'Nissan Altima', 22000.00, 'Nissan');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (6, 'BMW 3 Series', 40000.00, 'BMW');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (7, 'Audi A4', 42000.50, 'Audi');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (8, 'Mercedes-Benz C-Class', 45000.75, 'Mercedes-Benz');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (9, 'Kia Optima', 21000.25, 'Kia');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (10, 'Hyundai Sonata', 20000.00, 'Hyundai');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (11, 'Tesla Model 3', 50000.00, 'Tesla');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (12, 'Subaru Outback', 27000.50, 'Subaru');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (13, 'Mazda CX-5', 28000.75, 'Mazda');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (14, 'Volkswagen Golf', 24000.25, 'Volkswagen');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (15, 'Lexus ES', 38000.00, 'Lexus');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (16, 'Jeep Wrangler', 30000.50, 'Jeep');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (17, 'Chrysler 300', 29000.75, 'Chrysler');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (18, 'Volvo XC60', 36000.25, 'Volvo');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (19, 'Porsche 911', 90000.00, 'Porsche');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (20, 'Jaguar F-PACE', 55000.50, 'Jaguar');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (21, 'Land Rover Range Rover', 80000.75, 'Land Rover');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (22, 'Acura TLX', 32000.25, 'Acura');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (23, 'Infiniti Q50', 33000.00, 'Infiniti');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (24, 'Mitsubishi Outlander', 23000.50, 'Mitsubishi');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (25, 'Buick Encore', 26000.75, 'Buick');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (26, 'GMC Sierra', 36000.25, 'GMC');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (27, 'Cadillac XT5', 42000.00, 'Cadillac');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (28, 'Aston Martin DB11', 175000.50, 'Aston Martin');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (29, 'Ferrari 488 GTB', 300000.75, 'Ferrari');
INSERT INTO Cars (Id, Model, Price, Manufacturer) VALUES (30, 'Lamborghini Huracan', 250000.25, 'Lamborghini');
